spring:
  application:
    name: project
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8084


external-api:
  random-boolean-url: ${EXTERNAL_API_RANDOM_BOOLEAN_URL}
  postal-code-validation-url: ${EXTERNAL_API_POSTAL_CODE_VALIDATION_URL}


#external-api:
#  random-boolean-url: http://localhost:8080/
#  postal-code-validation-url: https://opencep.com/v1/


